### ISSUE TITLE
Doc about logic

### ISSUE THREAD

**Issue by xBorderie** [PrestaShop/docs#42] opened 2016-11-09 13:32 UTC
from @prestarocket on Gitter:

> is there any documentation for the new "logic" ( CategoryProductSearchProvider, ProductSearchQuery, ProductSearchContext etc...) ?

**Comment by matks** [comment] 2019-09-11 09:32
It seems to be a duplicate of https://github.com/PrestaShop/docs/issues/39

**Closed by matks** 2019-09-11 09:32 UTC
