### ISSUE TITLE
Add a page that informs what might grow in size on PrestaShop over time

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#1311] opened 2022-03-09 17:17 UTC
Some SQL tables of PrestaShop might become very big over time. Like `ps_log`, `ps_guest`, `ps_configuration`, `ps_connections` ... and system administrator might need to clean old obsolete data.

Also some folders might become very big due:
- image folders (for example does PrestaShop keeps images for archived/deleted products?)
- cache folders?
- var/logs ?

I think maybe it would be good to have a page that lists all these items.

I would like to know
- do you think this is a good idea?
- do you see some other items that might be eligible for this page?

I ping @marsaldev @Hlavtox @clotairer @okom3pom @jf-viguier and @PrestaShop/prestashop-maintainers

**Comment by jf-viguier** [comment] 2022-03-09 17:40
This is a very good idea and an automatic purge of old logs data should be great.
Orphans rows can also be deleted, like rows in product_lang with a deleted product or lang. I remember that there are some sql like that in ps_cleaner module.

**Comment by clotairer** [comment] 2022-03-09 17:43
Yeap good idea but I'm not sure documentation is the good place to explain why there's lots of slow loading page.

I prefer a page like performance page to see what's happend.

I share here my SQL request to purge data from connexion tables : 
```
DELETE c, cs FROM ps_connections c LEFT JOIN ps_connections_source cs ON (c.id_connections = cs.id_connections)       
    WHERE c.date_add < DATE_SUB(now(), INTERVAL 30 DAY);
OPTIMIZE TABLE ps_connections, ps_connections_source;
DELETE g  FROM ps_guest g LEFT JOIN ps_customer c ON (g.id_customer = c.id_customer)
    WHERE c.id_customer IS NULL;
OPTIMIZE TABLE ps_guest;
```

For ps_log table, there is a problem here https://github.com/PrestaShop/PrestaShop/blob/b459163e66f759da2c9640fd5730f9052ef61007/classes/PrestaShopLogger.php#L229 (slow query if you have a lot of data in this table especially if _PS_DISPLAY_COMPATIBILITY_WARNING_ is enabled). Sorry, spotted several weeks ago but no time to report an issue...

For cache directory, there is an old bug on smarty, but fixed now and new version seems good. But Smarty is not every time well used. Some developers used compilation as cache... (there is two distinct feature on smarty) It create lot of compiled templates and modules add some method to clean compiled templates. That's in my mind the main reason of problem of that.

For images, I've never had problem of disk spaces, but it could be nice to be able to clean this directory.

**Comment by matks** [comment] 2022-03-10 09:28
> I prefer a page like performance page to see what's happend.

<img src="https://h16free.com/wp-content/uploads/2018/08/why-not-both-meme.jpg">

Joke apart 😄  a devdocs page has some advantages: it can be found using google search engine, you can improve continuously (a part of the software needs a release to be updated) and more importantly it's a lot cheaper to do.

I have enough time now to add a new page to devdocs but not enough to build a full new BO page 😅  .

=> then I will do a doc page that can be improved over time 😉  but we can also keep the idea of a Performance page (maybe in a module) to be added inside the BO.

**Comment by marsaldev** [comment] 2022-03-10 10:19
A devdocs page is fundamental 😊

> I have enough time now to add a new page to devdocs but not enough to build a full new BO page 😅 .

Agree, but instead of new full BO page we can improve an existent one, maybe performance page, (for instance) with another box with buttons to clear tables, or logs, wdyt?

It would be nice to have an automatic check, but at the moment we have (like a possible solutions) cron with the check delegated to a script periodically (you can choose how much), or make a check everytime you browse an admin page that I wouldn't consider because it will critical impact the performance of BO

**Comment by clotairer** [comment] 2022-03-10 11:15
Edit about ps_logs:
- I reproduce on 1.7.8.4 slow query, (only) 200ms (that's quite long in my dev environment but 5s on a production env on 1.7.6.9 > I don't know mysql version) for PrestaShopLogger::addLog() with 300 000 logs on ps_log table.
- since 1.7.6.9, there is new where clause on isPresent() method like id_shop_group, that's probably involve a quicker query result just because it introduce a regression. In fact, with a monoshop the request cast id_shop_group but in database, id_shop_group is NULL. So the isPresent() request is quick now because it return always false ! No need for mysql to manage the filter by "message" TEXT type because id_shop_group never have 0 value instead NULL value).

I need to check on develop branch, explain it on an issue and find a solution with Core Team because we cannot add an multiple index on TEXT field type message.

So in my mind, no need to add a documentation on this part. Purge of logs is already available, and bug need to be fixed.

**Comment by Hlavtox** [comment] 2022-03-10 11:34
I think this could be a job of https://github.com/PrestaShop/pscleaner module, currently archived though. There is many things that should be checked/cleaned.

**Cleaning**
- Logs cleaned
- Mails cleaned
- Connections cleaned

**Maintenance/checking inconsistencies**
- Checking of dead lang entries. Checking of dead shop entries.
- Checking of default categories of products - if they are not deleted and are in product's categories.
- Checking of product's `id_manufacturer` for existence.
- Checking of correct `customizable`, `uploadable_files`, `text_fields`, `cache_is_pack`, `cache_default_attribute`, `cache_has_attachments `on `ps_product` table.
- Checking of dead feature values and attributes without their feature/attribute parents.
- Checking of product features that are deleted.
- Checking and repairing of category tree, nleft and nright.
- Checking and repairing of category position order.
- Checking if original image exists for every image in database
- and maybe others

> image folders (for example does PrestaShop keeps images for archived/deleted products?)

Images are physically deleted, if deleted from database. No problem there. 👍For disabled products - do not touch. A) you cannot know if somebody just flicked the switch. B) I keep product page available with a red "DISCONTINUED" message - ebay style.

**Comment by matks** [comment] 2022-03-30 09:37
First PR https://github.com/PrestaShop/docs/pull/1336 . It introduces the page and we could later make it grow.

**Closed as completed** 2022-03-30 16:25 UTC
Labels: question, Missing doc item
